version: "3"
services:

  postgres:
    container_name: pdf-api-database
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5432
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    restart: always
  api:
    container_name: pdf-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    expose:
      - "5000"
    depends_on:
      - postgres
    restart: always